import type { Metadata } from "next";
import Link from "next/link";
import { existsSync, readFileSync, statSync } from "node:fs";
import { resolve } from "node:path";
import { PageHeader, Card, Markdown, Notice } from "@/components/ui";
import { fmtDateTime } from "@/lib/ui/format";

export const metadata: Metadata = { title: "Readiness report" };
export const dynamic = "force-dynamic";

export default function ReadinessPage() {
  const path = resolve(process.cwd(), "docs", "READINESS_REPORT.md");
  const exists = existsSync(path);
  const text = exists ? readFileSync(path, "utf8") : null;
  const mtime = exists ? statSync(path).mtime.toISOString() : null;
  return (
    <>
      <PageHeader eyebrow="Academy" title="Readiness report" description="Generated by the eval harness (npm run evals:report). Rendered verbatim from docs/READINESS_REPORT.md." actions={<Link href="/academy" className="text-[12px] text-accent">← Academy</Link>} />
      {text ? (
        <Card>
          <div className="mb-3 text-[11px] text-faint">docs/READINESS_REPORT.md · updated {fmtDateTime(mtime)}</div>
          <Markdown text={text} />
        </Card>
      ) : (
        <Notice tone="warn" title="No readiness report yet">
          docs/READINESS_REPORT.md has not been generated. Run the evals and then <span className="mono">npm run evals:report</span>.
        </Notice>
      )}
    </>
  );
}
